---
title: "DeepLearning"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
install_keras()
```
keras --> api (application programming interface)

```{r}

```


# iris

```{r}
train = sample(1:150, 100)
x_train = as.matrix(iris[train, 1:4])
y_train = iris[train, 5]
x_test = as.matrix(iris[-train, 1:4])
y_test = iris[-train, 5]
y_train = to_categorical(as.integer(y_train)-1)
y_test = to_categorical(as.integer(y_test)-1)
```

```{r}
model = keras_model_sequential()
layer_dense(model, units = 5, activation = "relu", input_shape = 4)
layer_dense(model, units = 3, activation = "softmax")
compile(model, loss = "categorical_crossentropy", optimizer = optimizer_rmsprop(), metrics = "accuracy")
history = fit(model, x_train, y_train, epochs = 500, batch_size = 50, validation_split = 0.2)
#history = fit(model, x_train, y_train, epochs = 30, batch_size = 10)

```

# mnist

```{r}
mnist <- dataset_mnist()
rotate <- function(x) {
  t(apply(x, 2, rev))
}
image(1:28,1:28,rotate(mnist$train$x[1,,]),col=grey.colors(12))
mnist$train$y[1]
```


```{r}
x_train = mnist$train$x
x_test = mnist$test$x
y_train = mnist$train$y
y_test = mnist$test$y
# reshape
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))
# rescale
x_train <- x_train / 255
x_test <- x_test / 255
# output generation
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)
```

```{r}
hist(y_train)
hist(y_test)
```


```{r}
x_train <- array_reshape(x_train,c(nrow(x_train),784))
x_test <- array_reshape(x_train,c(nrow(x_test),784))

```










