---
title: "tp_lois"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ex1

```{r}
my_pois_one = function(x, n) {
  lambda = n
  u = runif(1)
  
  xi = dpois(x, lambda =  lambda)
  
  # il faut parcourir x dans le support
  # condition d'arrêt u < ppois(x, lambda = lambda)
  if (u > ppois(x, lambda = lambda)) {
    return(xi)
    }
  }

my_pois_one(10, 20.251)

```
coorection
```{r}
my_rpois_one = function(n) {
  u = runif(1)
  x = 0 
  while(u > ppois(x, lambda = n)) {
    x = x + 1
  }
  return(x)
}  

my_rpois_one(3.14)
```
accumulation
```{r}
my_rpois = function(n, lambda) {
  vec = rep(NA, length = n)
  
  for (i in 1:n) {
    vec[i] = my_rpois_one(n = lambda) # voir la fonction replicate pour éviter boucle for
  }
  return(vec)
}


n = 10000 # nb de nb aléatoire à tirer
# paramètre de la loi de poisson :
lambda = 3.14
x = my_rpois(n = n, lambda = lambda) # les tirer
plot(table(x)/n, type = "h") # diagramme baton (frequences)
mean(x) # on s'attends à proche de lambda
var(x) # on s'attends à proche de lambda

#vérifier les proportions observées
valx = 0:12
valy = dpois(valx, lambda = lambda)
points(valx, valy, col = "brown", pch = 19)

```


# 2.

```{r}
valx = seq(from = min(x), to = max(x), by = 1)
valy = dpois(valx, lambda = lambda)

x = c(-3, 1.3, 7, 15.2)
px = c(0.1, 0.4, 0.3, 0.2)
valrep_i = cumsum(px)


my_rdiscret_one = function() {

  # il faut parcourir x dans le support (x[1], x[2], .... x[i])
  # condition d'arret : u <= pX(xi)
  
  u = runif(1)
  i = 1 
  while(u > valrep_i[i]) {
    i = i + 1
  }
    return(x[i])
}

my_rdiscret_one()
```

























